spring:
  application:
    name: springboot_demo_rabbitmq

  profiles:
    active: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 60000

logging:
# 需要classpath下配置logback.xml，且logback.xml配置具体的各级别日志文件*.log
  path: log
  level:
    root: info
    org.springframework.boot: info



management:
#  security:
#    enabled: false
#    roles: ACTUATOR
  info:
    git:
      mode: simple

#endpoints:
#  health:
#    sensitive: false
#
#info:
#  app:
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
#
#security:
#  user:
#    name: admin
#    password: secret



